#!/bin/sh
set -e


# cc -Wall -Wextra -I./raylib-5.0_linux_amd64/include -Wl,-rpath=./raylib-5.0_linux_amd64/lib/ main.c -o main -L./raylib-5.0_linux_amd64/lib -l:libraylib.so
# cc -Wall -Wextra -I./raylib-5.0_linux_amd64/include main.c -o main -Wl,-rpath=./raylib-5.0_linux_amd64/lib/ -L./raylib-5.0_linux_amd64/lib -l:libraylib.so
# ./main

emcc -o ./web/game.html main.c -Os -Wall ./raylib/src/libraylib.a -I. -I./raylib/src -L. -L./raylib/src -s USE_GLFW=3 -s SAFE_HEAP=1 --shell-file ./raylib/src/minshell.html -DPLATFORM_WEB

python3 -m http.server 8080